version: '3.8'
services:
  docs-dev:
    # Usamos una imagen base de Node, no necesitamos construir con Nginx para desarrollo
    image: node:18-alpine
    container_name: rds-cube-docs-dev
    working_dir: /app
    # Montamos el código local en el contenedor para live-reloading
    volumes:
      - ./:/app
    ports:
      # Mapeamos el puerto de desarrollo de Astro a nuestro host
      - "4321:4321"
    # Comando para instalar dependencias y arrancar el servidor de desarrollo
    command: sh -c "npm install && npm run dev -- --host"